# Generated by Django 3.2.5 on 2021-08-06 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('link_checker', '0002_rename_title_url_urls'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='links_ok',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='url',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_urls', to='link_checker.project'),
        ),
    ]
