# Generated by Django 3.2.5 on 2021-08-13 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link_checker', '0003_auto_20210806_1632'),
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_of_update', models.DateField()),
            ],
        ),
    ]
